@url = https://urban-tribble-5g579vpqqv6q37gj9-3000.app.github.dev
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODI2NmFlYmZlY2UzMzFhNmU4NTkxOTkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDczNTI3MTIsImV4cCI6MTc0NzM2MzUxMn0.RuDoDdYJRlhNExiHChXd9xN3wT2jhRW5v9BlszJUBKQ


### 
GET {{url}}/api/users
Authorization: Bearer {{token}}

### Login User
POST {{url}}/api/users/login
content-type: application/json

{
    "email": "Nicolas44@gmail.com",
    "password": "senha123"
}